[project]
name = "randomtelecompayments"
version = "0.3.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beartype==0.22.9",
    "boto3==1.43.95",
    "fastapi[standard]==0.141.1",
    "fastparquet==2026.5.0",
    "idna==3.19",
    "ipykernel==7.3.0",
    "nbclient==0.11.0",
    "nbformat==5.11.1",
    "networkx==3.6.1",
    "numpy==2.5.3",
    "pandas==3.0.5",
    "pillow==12.3.0",
    "pyarrow==25.0.1",
    "pydantic-settings==2.15.0",
    "pygments==2.21.0",
    "python-dotenv==1.2.3",
    "python-multipart==0.0.32",
    "scikit-learn==1.9.1",
    "scipy==1.18.1",
    "seaborn==0.13.2",
    "shap==0.52.0",
    "starlette==1.6.0",
    "tabulate==0.10.0",
    "tornado==6.5.10",
    "unidecode==1.4.0",
    "urllib3==2.8.0",
]

[tool.uv]
exclude-newer = "7 days"

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes (basic syntax/runtime errors)
    "I",   # isort (import sorting)
    "B",   # flake8-bugbear (common design flaws)
    "C4",  # flake8-comprehensions (better list/dict comprehensions)
    "UP",  # pyupgrade (upgrades syntax to newer Python versions)
]
ignore = [
    "E402",
    "E501",
    "B018",
    "B006",
    "B904",
    "B008",
    "B017"
]
per-file-ignores = { }

[tool.ruff.format]
preview = false
