---
title: "QA Report"
format:
  html:
    code-fold: true
jupyter: python3
---

# Random Telecom Payments QA Report

```{python}
#| label: data-load
#|
import os
import sys
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# set file path for custom python modules
root_dir = os.path.dirname(os.path.dirname(os.path.join(os.getcwd())))
sys.path.append(os.path.join(root_dir, 'generator'))

import cons
import generator.qa as qa

# load data
pd.set_option('display.max_columns', None)
parse_dates = ['registration_date', 'transaction_date']
date_parser = lambda x: datetime.strptime(x, '%Y-%m-%d')
data = pd.read_csv(cons.fpath_randomtelecomtransdata,  parse_dates=parse_dates)
userdata = pd.read_parquet(cons.fpath_randomtelecomusersdata)

# show head of data
data.info()

# initialise QA object
qaUids = qa.Uids(data=data)
```

## Users

Check that the data makes sense and there are no anomalies at a user level.

### Unique UserIds per UID

There should be exactly one unique userid for every UID.

```{python}
#| label: nunique-user-ids-per-uid
qaUids.unique_user_ids()
```

### Unique Full Names per UID

There should be exactly one unique fullname for every UID.

```{python}
#| label: nunique-names-per-uid
qaUids.unique_names()
```

### Unique Registration Dates per UID

A user should register only on a single date.

```{python}
#| label: nunique-reg-dates-per-uid
qaUids.unique_reg_dates()
```

### Unique Registration Countries per UID

When registering the user should set their country code of residence.

```{python}
#| label: nunique-reg-countries-per-uid
qaUids.nunique_reg_countries()
```

### Unique Email Domains per UID

A user should register with a single email address corresponding to a single email domain.

```{python}
#| label: nunique-email-domains-per-uid
qaUids.unique_email_domains()
```

### Unique Device Hash per UID

A UID should have 1 to 3 devices.

```{python}
#| label: nunique-devices-per-uid
qaUids.unique_devices()
```

### Unique Card Hash per UID

A UID should have 1 to 2 cards, with an overall distribution less than the corresponding device hash distribution.

```{python}
#| label: nunique-cards-per-uid
qaUids.unique_cards()
```

### Unique IP Hash per UID

A UID should have between 1 and 10 ips.

```{python}
#| label: nunique-ips-per-uid
qaUids.unique_ips()
```

### Unique Application Hash per UID

```{python}
#| label: nunique-apps-per-uid
qaUids.unique_apps()
```

### Unique Transaction Hash per UID

```{python}
#| label: nunique-transactions-per-uid
qaUids.unique_transactions()
```

## Transaction

### Unique Transaction Hash

```{python}
unique_trans_hash_cnt = data['transaction_hash'].value_counts().sort_values(ascending=False).head()
sns.histplot(data=unique_trans_hash_cnt.to_frame(),x='count', bins = 10)
assert unique_trans_hash_cnt.max() == 1
assert unique_trans_hash_cnt.min() == 1
assert not unique_trans_hash_cnt.isnull().any()
```

### Unique Date per Transaction Hash

Each transaction hash should have a single date associated with it

```{python}
#| label: nunique-dates-per-trans
nunique_trans_dates_per_trans = data.groupby(by=['transaction_hash'], dropna=False, as_index=False).agg({'transaction_date':'nunique'})
sns.histplot(data=nunique_trans_dates_per_trans,x='transaction_date', bins = 20)
assert nunique_trans_dates_per_trans['transaction_date'].max() == 1
assert nunique_trans_dates_per_trans['transaction_date'].min() == 1
assert not nunique_trans_dates_per_trans['transaction_date'].isnull().any()
```

### Unique Amount per Transaction Hash

Each transaction hash should have a single transaction amount associated with it

```{python}
#| label: nunique-trans-amount-per-trans
nunique_trans_amounts_per_trans = data.groupby(by=['transaction_hash'], dropna=False, as_index=False).agg({'transaction_amount':'nunique'})
sns.histplot(data=nunique_trans_amounts_per_trans,x='transaction_amount', bins = 20)
assert nunique_trans_amounts_per_trans['transaction_amount'].max() == 1
assert nunique_trans_amounts_per_trans['transaction_amount'].min() == 1
assert not nunique_trans_amounts_per_trans['transaction_amount'].isnull().any()
```

### Unique Payment Method per Transaction Hash

Each transaction hash should have a single transaction payment method associated with it. Note, in some circumstances the payment method is missing as the transaction amount was 0.

```{python}
#| label: nunique-payment-method-per-trans
nunique_payment_method_per_trans = data.groupby(by=['transaction_hash'], dropna=False, as_index=False).agg({'transaction_payment_method':'nunique'}).sort_values('transaction_payment_method')
unique_payment_method_per_trans_hash = data.groupby(by=['card_type', 'transaction_payment_method'], as_index=False, dropna=False).agg({'transaction_hash':'size', 'transaction_amount':'sum'})
sns.histplot(data=nunique_payment_method_per_trans,x='transaction_payment_method', bins = 20)
assert nunique_payment_method_per_trans['transaction_payment_method'].max() == 1
assert nunique_payment_method_per_trans['transaction_payment_method'].min() == 0
assert not nunique_payment_method_per_trans['transaction_payment_method'].isnull().any()
assert unique_payment_method_per_trans_hash['card_type'].isnull().any()
assert unique_payment_method_per_trans_hash['card_type'].dropna().isin(['Mastercard', 'Visa']).all()
assert unique_payment_method_per_trans_hash['transaction_payment_method'].isnull().any()
assert unique_payment_method_per_trans_hash['transaction_payment_method'].dropna().isin(['Card', 'Points', 'Wallet']).all()
assert (unique_payment_method_per_trans_hash.loc[unique_payment_method_per_trans_hash['transaction_payment_method'].isnull(), 'transaction_amount'] == 0).all()
assert (unique_payment_method_per_trans_hash.loc[unique_payment_method_per_trans_hash['transaction_payment_method'].notnull(), 'transaction_amount'] > 0).all()
assert unique_payment_method_per_trans_hash.loc[unique_payment_method_per_trans_hash['transaction_payment_method'] == 'Card', 'card_type'].isin(['Mastercard', 'Visa']).all()
assert unique_payment_method_per_trans_hash.loc[unique_payment_method_per_trans_hash['transaction_payment_method'] != 'Card', 'card_type'].isnull().all()
print(unique_payment_method_per_trans_hash.to_markdown())
```

### Unique Payment Channel per Transaction Hash

Each transaction hash should have a single transaction payment channel with it. Note in some circumstances the payment channel is missing when the transaction amount is 0, or the payment method is wallet or points.

```{python}
#| label: nunique-payment-channel-per-trans
nunique_payment_channel_per_trans = data.groupby(by=['transaction_hash'], as_index=False).agg({'card_payment_channel':'nunique'}, dropna=False).sort_values('card_payment_channel')
unique_payment_channel_per_trans_hash = data.groupby(by=['transaction_payment_method', 'card_payment_channel'], as_index=False, dropna=False).agg({'transaction_hash':'size', 'transaction_amount':'sum'})
sns.histplot(data=nunique_payment_channel_per_trans,x='card_payment_channel', bins = 20)
assert nunique_payment_channel_per_trans['card_payment_channel'].max() == 1
assert nunique_payment_channel_per_trans['card_payment_channel'].min() == 0
assert not nunique_payment_channel_per_trans['card_payment_channel'].isnull().any()
assert unique_payment_channel_per_trans_hash['transaction_payment_method'].isnull().any()
assert unique_payment_channel_per_trans_hash['transaction_payment_method'].dropna().isin(['Card', 'Points', 'Wallet']).all()
assert unique_payment_channel_per_trans_hash['card_payment_channel'].isnull().any()
assert unique_payment_channel_per_trans_hash['card_payment_channel'].dropna().isin(['Adyen', 'AppStore', 'Docomo', 'PayPal', 'WorldPay']).all()
assert (unique_payment_channel_per_trans_hash.loc[unique_payment_channel_per_trans_hash['transaction_payment_method'].isnull(), 'transaction_amount'] == 0).all()
assert (unique_payment_channel_per_trans_hash.loc[unique_payment_channel_per_trans_hash['transaction_payment_method'].notnull(), 'transaction_amount'] > 0).all()
assert unique_payment_channel_per_trans_hash.loc[unique_payment_channel_per_trans_hash['transaction_payment_method'] == 'Card', 'card_payment_channel'].isin(['Adyen', 'AppStore', 'Docomo', 'PayPal', 'WorldPay']).all()
assert unique_payment_channel_per_trans_hash.loc[unique_payment_channel_per_trans_hash['transaction_payment_method'] != 'Card', 'card_payment_channel'].isnull().all()
print(unique_payment_channel_per_trans_hash.to_markdown())
```

### Unique Transaction Status per Transaction Hash

Each transaction hash should have a single unique payment status associated with it.

```{python}
#| label: nunique-trans-status-per-trans
nunique_trans_status_per_trans = data.groupby(by=['transaction_hash'], as_index=False).agg({'transaction_status':'nunique'})
unique_trans_status_per_trans_hash = data.groupby(by=['transaction_error_code', 'transaction_status'], as_index=False, dropna=False).size()
sns.histplot(data=nunique_trans_status_per_trans,x='transaction_status', bins = 20)
assert nunique_trans_status_per_trans['transaction_status'].max() == 1
assert nunique_trans_status_per_trans['transaction_status'].min() == 1
assert not nunique_trans_status_per_trans['transaction_status'].isnull().any()
assert unique_trans_status_per_trans_hash['transaction_error_code'].isnull().any()
assert unique_trans_status_per_trans_hash['transaction_error_code'].dropna().isin(['E900:ConnectionTimeout', 'E901:SuspectedFraud', 'E902:AuthenicationFailure', 'E903:UserCancelled', 'E904:InsufficientFunds']).all()
assert unique_trans_status_per_trans_hash['transaction_status'].notnull().all()
assert unique_trans_status_per_trans_hash['transaction_status'].dropna().isin(['Rejected', 'Pending', 'Successful']).all()
assert unique_trans_status_per_trans_hash.loc[unique_trans_status_per_trans_hash['transaction_error_code'].notnull(), 'transaction_status'].isin(['Rejected']).all()
assert unique_trans_status_per_trans_hash.loc[unique_trans_status_per_trans_hash['transaction_error_code'].isnull(), 'transaction_status'].isin(['Pending', 'Successful']).all()
print(unique_trans_status_per_trans_hash.to_markdown())
```

### Unique Error Codes Status per Transaction Hash

An error code should only be associated with transaction hashes with a failed payment status.

```{python}
#| label: nunique-errorcodes-per-trans
nunique_errorcodes_per_trans = data.groupby(by=['transaction_hash']).agg({'transaction_error_code':'nunique'}, dropna=False, as_index=False)
unique_error_codes_statuses_per_trans_hash = data.groupby(by=['transaction_error_code', 'transaction_status'], as_index=False, dropna=False).size()
sns.histplot(data=nunique_errorcodes_per_trans,x='transaction_error_code', bins = 20)
assert nunique_errorcodes_per_trans['transaction_error_code'].max() == 1
assert nunique_errorcodes_per_trans['transaction_error_code'].min() == 0
assert not nunique_errorcodes_per_trans['transaction_error_code'].isnull().any()
assert unique_error_codes_statuses_per_trans_hash['transaction_error_code'].isnull().any()
assert unique_error_codes_statuses_per_trans_hash['transaction_error_code'].dropna().isin(['E900:ConnectionTimeout', 'E901:SuspectedFraud', 'E902:AuthenicationFailure', 'E903:UserCancelled', 'E904:InsufficientFunds']).all()
assert unique_error_codes_statuses_per_trans_hash['transaction_status'].notnull().all()
assert unique_error_codes_statuses_per_trans_hash['transaction_status'].dropna().isin(['Rejected', 'Pending', 'Successful']).all()
assert unique_error_codes_statuses_per_trans_hash.loc[unique_error_codes_statuses_per_trans_hash['transaction_error_code'].notnull(), 'transaction_status'].isin(['Rejected']).all()
assert unique_error_codes_statuses_per_trans_hash.loc[unique_error_codes_statuses_per_trans_hash['transaction_error_code'].isnull(), 'transaction_status'].isin(['Pending', 'Successful']).all()
print(unique_error_codes_statuses_per_trans_hash.to_markdown())
```

### UIDs with High Device Hash Counts

```{python}
#| label: uid-max-device-trans-error-counts
nunique_devices_per_uid = data.groupby(by='uid', as_index=False).agg({'device_hash':'nunique'}).sort_values(by='device_hash')
uids_max_devices = data.loc[data['uid'].isin(nunique_devices_per_uid['uid'].tail()), :].sort_values(by=['uid', 'device_hash', 'transaction_date'])
uids_with_high_device_hash_counts = uids_max_devices.groupby(by=['userid'], as_index=False).agg({'device_hash':'nunique', 'transaction_hash':'count', 'transaction_error_code':'count'})
uids_with_high_device_hash_counts_error_codes = uids_max_devices.groupby(by=['transaction_error_code'], as_index=False).size().sort_values(by='size', ascending=False)
print(uids_with_high_device_hash_counts.to_markdown())
print(uids_with_high_device_hash_counts_error_codes.to_markdown())
```

### UIDs with High Card Hash Counts

```{python}
#| label: uid-max-card-trans-error-counts
nunique_cards_per_uid = data.groupby(by='uid', as_index=False).agg({'card_hash':'nunique'}).sort_values(by='card_hash')
uids_max_cards = data.loc[data['uid'].isin(nunique_cards_per_uid['uid'].tail()), :].sort_values(by=['uid', 'card_hash', 'transaction_date'])
uids_with_high_card_hash_counts = uids_max_cards.groupby(by=['userid'], as_index=False).agg({'card_hash':'nunique', 'transaction_hash':'count', 'transaction_error_code':'count'})
uids_with_high_card_hash_counts_error_codes = uids_max_cards.groupby(by=['transaction_error_code'], as_index=False).size().sort_values(by='size', ascending=False)
print(uids_with_high_card_hash_counts.to_markdown())
print(uids_with_high_card_hash_counts_error_codes.to_markdown())
```


### UIDs with High IP Hash Counts

```{python}
#| label: uid-max-ip-trans-error-counts
nunique_ips_per_uid = data.groupby(by='uid', as_index=False, dropna=False).agg({'ip_hash':'nunique'}).sort_values(by='ip_hash')
uids_max_ips = data.loc[data['uid'].isin(nunique_ips_per_uid['uid'].tail()), :].sort_values(by=['uid', 'ip_hash', 'transaction_date'])
uids_with_high_ip_hash_counts = uids_max_ips.groupby(by=['userid'], as_index=False).agg({'ip_hash':'nunique', 'transaction_hash':'count', 'transaction_error_code':'count'})
uids_with_high_ip_hash_counts_error_codes = uids_max_ips.groupby(by=['transaction_error_code'], as_index=False).size().sort_values(by='size', ascending=False)
print(uids_with_high_ip_hash_counts.to_markdown())
print(uids_with_high_ip_hash_counts_error_codes.to_markdown())
```

## Card

### Unique Card Types per Card Hashes

Each card should have a single card type associated with it.

```{python}
#| label: nunique-card-types-per-card
nunique_card_types_per_card = data.groupby(by=['card_hash'], as_index=False, dropna=False).agg({'card_type':'nunique'})
sns.histplot(data=nunique_card_types_per_card,x='card_type', bins = 20)
data.groupby(by=['card_type', 'transaction_payment_method'], as_index=False, dropna=False).agg({'transaction_hash':'size', 'transaction_amount':'sum'})
assert nunique_card_types_per_card['card_type'].max() == 1
assert nunique_card_types_per_card['card_type'].min() == 0
assert not nunique_card_types_per_card['card_type'].isnull().any()
```


### Unique Country Code per Card Hashes

Each card should have a single country code associated with it.

```{python}
#| label: nunique-country-codes-per-card
nunique_country_codes_per_card = data.groupby(by=['card_hash'], as_index=False, dropna=False).agg({'card_country_code':'nunique'})
sns.histplot(data=nunique_country_codes_per_card,x='card_country_code', bins = 20)
data.assign(card_country_code=data['card_country_code'].notnull().astype(int)).groupby(by=['card_country_code', 'transaction_payment_method'], as_index=False, dropna=False).agg({'transaction_hash':'size', 'transaction_amount':'sum'})
assert nunique_country_codes_per_card['card_country_code'].max() == 1
assert nunique_country_codes_per_card['card_country_code'].min() == 0
assert not nunique_country_codes_per_card['card_country_code'].isnull().any()
```

## IP

### Unique Country Codes per IP Hashes

Each IP should have a single country code associated with it.

```{python}
#| label: nunique-country-codes-per-ip
nunique_country_codes_per_ip = data.groupby(by=['ip_hash'], as_index=False, dropna=False).agg({'ip_country_code':'nunique'})
sns.histplot(data=nunique_country_codes_per_ip,x='ip_country_code', bins = 20)
data.groupby(by=['ip_country_code'], as_index=False, dropna=False).size()
assert nunique_country_codes_per_ip['ip_country_code'].max() == 1
assert nunique_country_codes_per_ip['ip_country_code'].min() == 1
assert not nunique_country_codes_per_ip['ip_country_code'].isnull().any()
```
