name: Development Workflow
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ dev, main ]

jobs:

  ruff-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run Ruff Checks
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89
        with:
          version: "0.15.15"

  sonarqube-scan:
    runs-on: ubuntu-latest # cite: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # cite: 2
        with:
          fetch-depth: 0 # Required by SonarQube to calculate blame/git history
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=my-project-key
            -Dsonar.sources=.

  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Run Trivy to show all vulnerabilities
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        exit-code: '0'
    - name: Fail build on High or Critical vulnerabilities
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'

  python-unittests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Set environment variable
      run: echo "GITHUB_ACTIONS_UNITTEST_FLAG=1" >> $GITHUB_ENV
    - name: Install uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        uv sync
    - name: Test with unittest
      run: |
        uv run python -m unittest discover ./generator/unittests/utilities
        uv run python -m unittest discover ./generator/unittests/objects
        uv run python -m unittest discover ./generator/unittests/app