name: Development Workflow
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ dev, main ]

jobs:

  ruff-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run Ruff Checks
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89
        with:
          version: "0.15.15"

  sonarqube-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Check if SonarQube is Online
        id: check-sonar
        run: |
          if curl --output /dev/null --silent --head --fail --connect-timeout 5 "${{ secrets.SONAR_HOST_URL }}/api/system/status"; then
            echo "online=true" >> $GITHUB_OUTPUT
          else
            echo "SonarQube server is offline or unreachable."
            echo "online=false" >> $GITHUB_OUTPUT
          fi
      - name: Run SonarQube Scan
        if: steps.check-sonar.outputs.online == 'true'
        timeout-minutes: 3
        env:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        shell: cmd
        run: |
          sonar-scanner.bat -D"sonar.projectKey=%SONAR_PROJECT_KEY%" -D"sonar.sources=." -D"sonar.host.url=%SONAR_HOST_URL%" -D"sonar.token=%SONAR_TOKEN%"

  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Run Trivy to show all vulnerabilities
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        exit-code: '0'
    - name: Fail build on High or Critical vulnerabilities
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'

  python-unittests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Set environment variable
      run: echo "GITHUB_ACTIONS_UNITTEST_FLAG=1" >> $GITHUB_ENV
    - name: Install uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        uv sync
    - name: Test with unittest
      run: |
        uv run python -m unittest discover ./generator/unittests/utilities
        uv run python -m unittest discover ./generator/unittests/objects
        uv run python -m unittest discover ./generator/unittests/app